### ISSUE TITLE
Exception on open IndexedDB

### ISSUE THREAD

**Issue by a-kriya** [vladlavrik/netify#13]
I get the following errors when I try to open the Netify tab in the DevTools:

![image](https://user-images.githubusercontent.com/26761352/117588495-4398a580-b141-11eb-93d2-8c543bb4fe54.png)

It may be related to the browser build or config. Here's my version:

```
Version 90.0.4430.93 (Developer Build, ungoogled-chromium) built on Ubuntu focal/20.04, running on linuxmint ulyssa/20.1 (64-bit)
```

To verify some basic IndexedDB operations, I used https://mdn.github.io/to-do-notifications/ without any issues.

**Comment by vladlavrik** [comment]
Thank you for your report.
Unfortunately, now there is no way to check on the software you specified.
I suspect this is due to the special privacy conditions in this browser.
You can open the Inspector for Netify by right mouse clicking in the Netify panel area and clicking Inspect element.
There should be an error in the opened consoles with a more detailed description.
If you give me this information it will greatly help me in solving this problem.
I am especially interested in the place where this error occurred.

**Comment by vladlavrik** [comment]
Netify is currently able to work without accessing the indexedDB database. I'm closing this issue, if you're still having trouble with this, please let me know
