### ISSUE TITLE
Listener status resets on reload

### ISSUE THREAD

**Issue by connect192168** [vladlavrik/netify#5]
When I reload a webpage to check that a rule works, the listener resets to inactive.
This means that I have to quickly re-activate the listener and hope that no requests got through before I turned the listener on.

I don't know a ton about how this plugin works, but thank you for making it, it's really useful.

**Comment by vladlavrik** [comment]
Thank you for your feedback.
Unfortunately, I Can not reproduce this problem, there are probably some specific conditions when this occurs.
Could you describe your conditions in more detail?
For example:
- is it localhost or not?
- is the "Rules per site" checkbox active?
- is there a dependency on the rule (filter and actions)?
- are there any conditions in which this problem does not appear?

When trying to catch the problem, I came across many other oddities in working with Chrome Devtools Protocol introduced in the latest version of Chrome.
Perhaps your problem is also related to this.
Unfortunately, this is a fee for using experimental technologies.

In any case I will try to catch and fix of this problem.

**Comment by connect192168** [comment]
it's not localhost
rules per site is on

Test 1:
I did a test with this page (blocking profile icons using 
The rule was `*.githubusercontent.com*` -> failed.
Netify switched to inactive as soon as the page finished loading.
(video of what I did : https://youtu.be/lTuPyEaib-g )

Test 2:
I also did a test with the original page that I had the problem with.
(I had to hide and redact a fair bit of the page because it had PII)
The rule I used was `https://secure.gravatar.*` -> failed.
I turn listening on and referesh the page.
Netify switches to inactive, the page finishes loading, I switch to the network tab and show that a network request (that a netify rule was supposed to block) got 200 instead of failed. (video of what I did : https://youtu.be/5lLMh18KLn4 )

Extension errors:
I opened devtools console on the netify devtools tab (whent to the render of the netify panel, Ctrl+shift+I, navigate to console) and found the following 2 errors:
`DevTools failed to load SourceMap: Could not load content for chrome-extension://mdafhjaillpdogjdigdkmnoddeoegblj/panel.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
12:51:02.268 DevTools failed to load SourceMap: Could not load content for chrome-extension://mdafhjaillpdogjdigdkmnoddeoegblj/main.css.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

Issues I've had but fixed:
My copy of chrome has most of the privacy settings locked down, so the above errors might be another issue that only occurs on my setup.
I had to add `chrome-extension://mdafhjaillpdogjdigdkmnoddeoegblj/` to the allow list for cookies and other site data before chrome would even let me load the netify tab. because I had cookies set to `block all third-party` in chrome settings)
![image](https://user-images.githubusercontent.com/38689351/90632435-50284700-e21c-11ea-8c34-4f0a037f186e.png)
