### ISSUE TITLE
Does it work in Chrome 86?

### ISSUE THREAD

**Issue by sergej-s** [vladlavrik/netify#8]
I can say that your extension is quite awesome!
Unfortunately it gets stuck in Chrome 86. Is this correct or Im doing something wrong?
It just blocks request and nothing happens.

In v85 it works like a charm.

**Comment by vladlavrik** [comment]
Thanks for the feedback)
I checked and it works for me.

Please provide more information.
- Are there any other extensions? If there is, is there a problem if you turn them off?
- What actions and what filter is specified in the rules used?
- In the context of which domain is it used (or is there a dependency on the domain and protocol)?

If it possible, you can record a small video demo of the problem, it helps a lot.

**Comment by sergej-s** [comment]
@vladlavrik thanks for reply!
- no extensions, clean chrome v86.
- xhrrequest with json payload
- ...
here is the [video](https://www.dropbox.com/s/i8c5kjgxnrtsde3/Screen%20Recording%202020-10-20%20at%2011.13.30.mov?dl=0). 
It was working in chrome v85 with the same parms.

**Comment by vladlavrik** [comment]
@sergej-s thanks for the detailed information.
I found the cause of the problem, in this update. With this update, Chrome started accepting base64 encoded request body instead of plain text as it was before.
Unfortunately, it did it in silence. The API used is still not stable, therefore, such problems appear periodically.
I will fix this problem shortly.
For now, as a temporary solution, you can use the base64 encoded value.

**Comment by sergej-s** [comment]
Many thanks for reply! it works with base64 values, huh we can continue use your magnificent tool! :rocket:

**Comment by vladlavrik** [comment]
Today the extension has been updated in the web store to version 0.2.2, where this problem has been fixed.
